# Generated by Django 5.1.15 on 2026-09-17 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editorial', '0004_application_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('because', models.CharField(blank=True, max_length=200)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to=settings.AUTH_USER_MODEL)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['member', 'rank'], name='recommend_s_member__321fee_idx')],
                'unique_together': {('member', 'other')},
            },
        ),
        migrations.CreateModel(
            name='SuggestedJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('because', models.CharField(blank=True, max_length=200)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_to', to='editorial.journal')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['member', 'rank'], name='recommend_s_member__525e0b_idx')],
                'unique_together': {('member', 'journal')},
            },
        ),
    ]
