# Generated by Django 5.1.15 on 2026-09-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applying_for', models.CharField(blank=True, max_length=120)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('stated_designation', models.CharField(blank=True, max_length=200)),
                ('stated_department', models.CharField(blank=True, max_length=200)),
                ('stated_affiliation', models.CharField(blank=True, max_length=255)),
                ('wp_entry_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stated_title', models.CharField(blank=True, max_length=300)),
                ('preference', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['preference'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=60)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('wp_entry_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('abbreviation', models.CharField(blank=True, max_length=80)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=800)),
                ('status', models.CharField(blank=True, max_length=60)),
                ('wp_entry_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
