# Generated by Django 5.1.15 on 2026-09-17 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['journal', 'role'], name='editorial_a_journal_561561_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['member', 'ended_on'], name='editorial_a_member__ed554f_idx'),
        ),
    ]
