# Generated by Django 5.1.15 on 2026-09-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0003_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
