# Generated by Django 5.1.15 on 2026-10-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0005_applicationjournal_per_choice_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, max_length=500, upload_to='applications/'),
        ),
    ]
