# Generated by Django 5.1.15 on 2026-10-03 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0006_application_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('designation', models.CharField(default='Commissioning Editor', max_length=120)),
                ('signature_image', models.ImageField(blank=True, upload_to='signatures/')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Editorial staff member',
                'verbose_name_plural': 'Editorial staff',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='journal',
            name='commissioning_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to='editorial.editorialstaff'),
        ),
    ]
