# Generated by Django 5.1.15 on 2026-10-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0007_editorialstaff_journal_commissioning_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherImprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(help_text="Must match Journal.publisher exactly, e.g. 'STM Journals'.", max_length=200, unique=True)),
                ('signatory_name', models.CharField(max_length=200)),
                ('signatory_title', models.CharField(blank=True, max_length=255)),
                ('imprint_name', models.CharField(default='Consortium e-Learning Network Pvt Ltd', help_text='The company the letter is issued on behalf of.', max_length=200)),
                ('address', models.TextField(blank=True, help_text='Printed in the letter footer.')),
                ('signature_image', models.ImageField(blank=True, upload_to='imprints/')),
                ('stamp_image', models.ImageField(blank=True, upload_to='imprints/')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publisher signature block',
                'verbose_name_plural': 'Publisher signature blocks',
                'ordering': ['publisher'],
            },
        ),
    ]
