# Generated by Django 5.1.15 on 2026-09-16 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('profession', models.CharField(blank=True, max_length=120)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('affiliation_url', models.URLField(blank=True, max_length=500)),
                ('affiliation_logo', models.CharField(blank=True, max_length=500)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=160)),
                ('experience_years', models.CharField(blank=True, max_length=40)),
                ('institutional_profile_url', models.URLField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('academic_qualification', models.CharField(blank=True, max_length=160)),
                ('academic_university', models.CharField(blank=True, max_length=255)),
                ('qualification_year', models.CharField(blank=True, max_length=10)),
                ('expertise', models.TextField(blank=True)),
                ('areas_of_interest', models.TextField(blank=True)),
                ('biography', models.TextField(blank=True)),
                ('picture', models.CharField(blank=True, max_length=500)),
                ('orcid', models.CharField(blank=True, db_index=True, max_length=40)),
                ('google_scholar_id', models.CharField(blank=True, max_length=80)),
                ('researchgate_id', models.CharField(blank=True, max_length=120)),
                ('ssrn_id', models.CharField(blank=True, max_length=80)),
                ('scopus_id', models.CharField(blank=True, max_length=80)),
                ('wants_editorial_board', models.BooleanField(null=True)),
                ('wp_entry_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=160)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('wp_entry_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='profiles.profile')),
            ],
        ),
    ]
