# Generated by Django 5.1.15 on 2026-10-07 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_cv_sections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimedRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_entry_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('kind', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('journal', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(blank=True, max_length=60)),
                ('journal_url', models.URLField(blank=True, max_length=500)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('remark', models.TextField(blank=True)),
                ('source_form', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_entry_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('abbreviation', models.CharField(blank=True, max_length=60)),
                ('paper_title', models.CharField(blank=True, max_length=500)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('papers_count', models.IntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_on'],
            },
        ),
    ]
