# Generated by Django 5.1.15 on 2026-09-16 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.URLField(blank=True, max_length=1000)),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('doi', models.CharField(blank=True, db_index=True, max_length=120)),
                ('wp_form_id', models.IntegerField(blank=True, null=True)),
                ('wp_entry_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
    ]
