# Generated by Django 5.1.15 on 2026-10-03 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_member_referred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('to_address', models.CharField(db_index=True, max_length=320)),
                ('from_address', models.CharField(blank=True, max_length=320)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True)),
                ('kind', models.CharField(blank=True, db_index=True, help_text='Loose tag — login_credentials, password_reset, …', max_length=60)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('outbox', 'Outbox')], db_index=True, default='sent', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('related_member', models.ForeignKey(blank=True, help_text='The APID member the message was sent to, when there is one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['-sent_at'], name='identity_em_sent_at_ed14c3_idx')],
            },
        ),
    ]
