# Generated by Django 5.1.15 on 2026-10-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, help_text='Slug: login_credentials, welcome, …', max_length=60, unique=True)),
                ('name', models.CharField(help_text='What the office sees in the editor.', max_length=120)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('variables_help', models.TextField(blank=True, help_text='Short note on which {placeholders} the sender provides.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
