# Generated by Django 5.1.15 on 2026-10-07 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('issue', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('reply', models.TextField(blank=True)),
                ('help_id', models.IntegerField(blank=True, null=True)),
                ('wp_entry_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
