"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['APID_SECRET_KEY']

# Off unless a developer asks for it. The default is the safe one, so forgetting to
# set anything cannot put a debug page carrying 13,412 members' data on a public host.
DEBUG = os.environ.get("APID_DEBUG", "") == "1"

ALLOWED_HOSTS = ["apid.journalslibrary.com", "apid.celnet.in", "127.0.0.1", "localhost"]
CSRF_TRUSTED_ORIGINS = ["https://apid.journalslibrary.com", "https://apid.celnet.in"]

# Behind Caddy, which terminates TLS and sets this.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

#: While the site is being built, nobody outside the office should be able to read
#: 13,412 people's profiles on a URL somebody guesses. Set to "0" the day Amit says the
#: public pages are ready — not before, and not by default.
APID_PUBLIC = os.environ.get("APID_PUBLIC", "") == "1"


# Application definition

INSTALLED_APPS = [
    "apps.identity",
    "apps.profiles",
    "apps.works",
    "apps.editorial",
    "apps.social",
    "apps.recommend",
    "apps.migration",
    "apps.content",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves /static/ from the app rather than from Caddy: one fewer place where a
    # deploy can be half-done, and this site's static files are a few admin assets.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Last, so it can see an authenticated user. Closed by default; see the module.
    'apps.identity.middleware.SignedInOnly',
]

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/me/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.media',
                'apps.editorial.context.office',
                'apps.social.context.notifications',
                'apps.identity.context_processors.impersonation',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import os
import urllib.parse as _urlparse


def _db_url() -> str:
    """The APID database, from the file the container's password was written to.

    Never a default that quietly works: a missing credentials file must stop the
    command, not send it to a stray SQLite that looks like a successful import.
    """
    env = BASE_DIR.parent / ".env.db"
    if env.exists():
        for line in env.read_text().splitlines():
            if line.startswith("APID_DB_URL="):
                return line.split("=", 1)[1].strip()
    raise RuntimeError(f"No APID_DB_URL in {env}")


_url = _urlparse.urlparse(os.environ.get("APID_DB_URL") or _db_url())
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": _url.path.lstrip("/"),
        "USER": _url.username,
        "PASSWORD": _url.password,
        "HOST": _url.hostname,
        "PORT": _url.port,
        "CONN_MAX_AGE": 60,
    }
}

# The member *is* the user: sign-in, identity and the public record are one thing.
AUTH_USER_MODEL = "identity.Member"

# Django's default first, so a password set here is written in Django's scheme, and
# the WordPress reader last, so an imported member can still sign in with what they
# already have. `must_update` on the legacy hasher means the first successful sign-in
# rewrites it — the old hashes drain away instead of living for ever.
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "apps.identity.hashers.WordPressHasher",
]


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# The uploads copied out of WordPress. Served from where the migration put them, so
# the pictures work before any decision about long-term storage is made.
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR.parent / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

# Email via AWS SES (shared claw-ops IAM, eu-west-1, mail.celnet.in verified domain).
# Falls back to console backend if AWS creds are not set — the app still boots in dev.
if os.environ.get("APID_AWS_ACCESS_KEY_ID"):
    EMAIL_BACKEND = "django_ses.SESBackend"
    AWS_ACCESS_KEY_ID = os.environ["APID_AWS_ACCESS_KEY_ID"]
    AWS_SECRET_ACCESS_KEY = os.environ.get("APID_AWS_SECRET_ACCESS_KEY", "")
    AWS_SES_REGION_NAME = os.environ.get("APID_AWS_SES_REGION_NAME", "eu-west-1")
    AWS_SES_REGION_ENDPOINT = f"email.{AWS_SES_REGION_NAME}.amazonaws.com"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = os.environ.get("APID_DEFAULT_FROM_EMAIL",
                                    "APID <no-reply@mail.celnet.in>")
SERVER_EMAIL = DEFAULT_FROM_EMAIL
PASSWORD_RESET_TIMEOUT = 60 * 60 * 2  # 2 hours; short enough that a copied link rots

#: Username or email, with the duplicate-email rule spelled out in the module.
AUTHENTICATION_BACKENDS = ["apps.identity.backends.UsernameOrEmailBackend"]
